# Generated by Django 3.2 on 2023-10-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id_capteur', models.AutoField(primary_key=True, serialize=False)),
                ('etat_bouton', models.IntegerField()),
                ('tempÚrature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'capteur',
                'managed': False,
            },
        ),
    ]
